/*
Created: 23/06/2015
Modified: 14/08/2017
Model: PostgreSQL 9.3
Database: PostgreSQL 9.3
*/


-- Create tables section -------------------------------------------------

-- Table GLUO_ANO_FISCAL

CREATE TABLE GLUO_ANO_FISCAL(
 ANOF_ID Serial NOT NULL,
 ANO_FISCAL Integer NOT NULL,
 DESCRIPCION Varchar,
 FECHA_INCIO_ANO_FISCAL Date NOT NULL,
 ESTADO Character(1) NOT NULL,
 ACTIVO Character(1),
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 EMPR_ID Integer NOT NULL,
 VALOR_SALARIO_MINIMO Numeric(16,2) NOT NULL
)
;
COMMENT ON COLUMN GLUO_ANO_FISCAL.ESTADO IS 'A=ABIERTO
C=CERRADO'
;

-- Create indexes for table GLUO_ANO_FISCAL

CREATE INDEX IX_EMPR_ANOF ON GLUO_ANO_FISCAL (EMPR_ID)
;

-- Add keys for table GLUO_ANO_FISCAL

ALTER TABLE GLUO_ANO_FISCAL ADD CONSTRAINT PK_ANOF PRIMARY KEY (ANOF_ID)
;

ALTER TABLE GLUO_ANO_FISCAL ADD CONSTRAINT UK_ANOF UNIQUE (ANO_FISCAL,EMPR_ID)
;

-- Table GLUO_PRESUPUESTO

CREATE TABLE GLUO_PRESUPUESTO(
 PPTO_ID Serial NOT NULL,
 APROBADO Character(1) DEFAULT 'N' NOT NULL,
 USU_APROBADOR Integer,
 ACTIVO Character(1),
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 ANOF_ID Integer NOT NULL,
 TIPP_ID Integer NOT NULL,
 CONTABILIZADO Character(1) DEFAULT 'N' NOT NULL
)
;
COMMENT ON COLUMN GLUO_PRESUPUESTO.APROBADO IS 'EL PRESUPUESTO ESTA APROBADO?
UNA CONDICION PARA APROBARLO, ES QUE EL PRESUPUESTO SE ENCUENTRE EQUILIBRADO, ES DECIR QUE LA SUMATORIA DE LOS INGRESOS SEA IGUAL A LA SUMATORIA DE GASTOS'
;
COMMENT ON COLUMN GLUO_PRESUPUESTO.USU_APROBADOR IS 'USUARIO QUE APRUBA EL PRESUPUESTO'
;

-- Create indexes for table GLUO_PRESUPUESTO

CREATE INDEX IX_ANOF_PPTO ON GLUO_PRESUPUESTO (ANOF_ID)
;

CREATE INDEX IX_TIPP_PPTO ON GLUO_PRESUPUESTO (TIPP_ID)
;

-- Add keys for table GLUO_PRESUPUESTO

ALTER TABLE GLUO_PRESUPUESTO ADD CONSTRAINT PK_PPTO PRIMARY KEY (PPTO_ID)
;

-- Table GLUO_DETALLE_PRESUPUESTO

CREATE TABLE GLUO_DETALLE_PRESUPUESTO(
 DPTO_ID Serial NOT NULL,
 CODIGO_CUENTA Varchar NOT NULL,
 DESCRIPCION_CUENTA Varchar NOT NULL,
 VALOR_INICIAL Numeric(16,2) NOT NULL,
 SALDO_EN_CDPS Numeric(16,2) NOT NULL,
 VALOR_DESPUES_DE_MODIFICACIONES Numeric(16,2) NOT NULL,
 VALOR_APLAZADO Numeric(16,2) NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 PPTO_ID Integer NOT NULL,
 DPTO_ID_PADRE Integer,
 TIRE_ID Integer,
 SECT_ID Integer,
 TIPO_TRANSFERENCIA Character(1)
)
;
COMMENT ON COLUMN GLUO_DETALLE_PRESUPUESTO.VALOR_INICIAL IS 'VALOR INICIAL APROBADO DEL CODIGO PRESUPUESTAL'
;
COMMENT ON COLUMN GLUO_DETALLE_PRESUPUESTO.SALDO_EN_CDPS IS 'VALOR QUE SE ACUMULA PARA ESTE RUBRO EN CDPs'
;
COMMENT ON COLUMN GLUO_DETALLE_PRESUPUESTO.VALOR_DESPUES_DE_MODIFICACIONES IS 'VALOR DESPUES DE HACER ADICIONES, REDUCCIONES PARA ESTE RUBRO'
;
COMMENT ON COLUMN GLUO_DETALLE_PRESUPUESTO.VALOR_APLAZADO IS 'CONTIENE EL VALOR APLAZADO DE ESTE RUBRO. DEBE ASEGURARSE QUE EL SALDO DE ESTE RUBRO, SEA SIEMPRE MAYOR O IGUAL AL VALOR APLAZADO, ESTO CON EL FIN DE GARANTIZAR QUE SE CONGELE EL VALOR APLAZADO.'
;

-- Create indexes for table GLUO_DETALLE_PRESUPUESTO

CREATE INDEX IX_PPTO_DPTO ON GLUO_DETALLE_PRESUPUESTO (PPTO_ID)
;

CREATE INDEX IX_DPTO_DPTO ON GLUO_DETALLE_PRESUPUESTO (DPTO_ID_PADRE)
;

CREATE INDEX IX_TIRE_DPTO ON GLUO_DETALLE_PRESUPUESTO (TIRE_ID)
;

CREATE INDEX IX_SECT_DPTO ON GLUO_DETALLE_PRESUPUESTO (SECT_ID)
;

-- Add keys for table GLUO_DETALLE_PRESUPUESTO

ALTER TABLE GLUO_DETALLE_PRESUPUESTO ADD CONSTRAINT PK_DPTO PRIMARY KEY (DPTO_ID)
;

-- Table GLUO_PLAN_DESARROLLO

CREATE TABLE GLUO_PLAN_DESARROLLO(
 PLAN_ID Serial NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 NOMBRE_ALCALDE Varchar NOT NULL,
 ESLOGAN Varchar,
 DESCRIPCION Varchar,
 ANO_INICIO Date NOT NULL,
 ANO_FIN Date NOT NULL
)
;

-- Add keys for table GLUO_PLAN_DESARROLLO

ALTER TABLE GLUO_PLAN_DESARROLLO ADD CONSTRAINT PK_PLAN PRIMARY KEY (PLAN_ID)
;

-- Table SEG_USUARIO

CREATE TABLE SEG_USUARIO(
 USU_ID Serial NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 USU_LOGIN Varchar NOT NULL,
 USU_PASSWORD Varchar NOT NULL
)
;

-- Add keys for table SEG_USUARIO

ALTER TABLE SEG_USUARIO ADD CONSTRAINT PK_USU PRIMARY KEY (USU_ID)
;

-- Table SEG_ROL

CREATE TABLE SEG_ROL(
 ROL_ID Serial NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 NOMBRE Varchar NOT NULL
)
;

-- Add keys for table SEG_ROL

ALTER TABLE SEG_ROL ADD CONSTRAINT PK_ROL PRIMARY KEY (ROL_ID)
;

-- Table SEG_ROL_USUARIO

CREATE TABLE SEG_ROL_USUARIO(
 RLUS_ID Serial NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 USU_ID Integer NOT NULL,
 ROL_ID Integer NOT NULL
)
;

-- Create indexes for table SEG_ROL_USUARIO

CREATE INDEX IX_USU_ID ON SEG_ROL_USUARIO (USU_ID)
;

CREATE INDEX IX_ROL_ID ON SEG_ROL_USUARIO (ROL_ID)
;

-- Add keys for table SEG_ROL_USUARIO

ALTER TABLE SEG_ROL_USUARIO ADD CONSTRAINT PK_RLUS PRIMARY KEY (RLUS_ID)
;

-- Table SEG_OPCION

CREATE TABLE SEG_OPCION(
 OPCN_ID Serial NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 NOMBRE Varchar NOT NULL
)
;

-- Add keys for table SEG_OPCION

ALTER TABLE SEG_OPCION ADD CONSTRAINT PK_OPCN PRIMARY KEY (OPCN_ID)
;

-- Table SEG_PERMISO

CREATE TABLE SEG_PERMISO(
 PERM_ID Serial NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 USU_ID Serial NOT NULL,
 ROL_ID Serial NOT NULL,
 OPCN_ID Integer NOT NULL,
 RLUS_ID Integer NOT NULL
)
;

-- Create indexes for table SEG_PERMISO

CREATE INDEX IX_OPCN_ID ON SEG_PERMISO (OPCN_ID)
;

CREATE INDEX IX_RLUS_ID ON SEG_PERMISO (RLUS_ID)
;

-- Add keys for table SEG_PERMISO

ALTER TABLE SEG_PERMISO ADD CONSTRAINT PK_PERM PRIMARY KEY (PERM_ID)
;

-- Table GLUO_SECTOR_EJE_DIMENSION

CREATE TABLE GLUO_SECTOR_EJE_DIMENSION(
 SEDI_ID Serial NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 PLAN_ID Integer NOT NULL,
 DESCRIPCION Varchar NOT NULL
)
;

-- Create indexes for table GLUO_SECTOR_EJE_DIMENSION

CREATE INDEX IX_PLAN_ID ON GLUO_SECTOR_EJE_DIMENSION (PLAN_ID)
;

-- Add keys for table GLUO_SECTOR_EJE_DIMENSION

ALTER TABLE GLUO_SECTOR_EJE_DIMENSION ADD CONSTRAINT PK_SEDI PRIMARY KEY (SEDI_ID)
;

-- Table GLUO_OBJETIVO

CREATE TABLE GLUO_OBJETIVO(
 OBJE_ID Serial NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 SEDI_ID Integer NOT NULL,
 DESCRIPCION Varchar NOT NULL
)
;

-- Create indexes for table GLUO_OBJETIVO

CREATE INDEX IX_SEDI_ID ON GLUO_OBJETIVO (SEDI_ID)
;

-- Add keys for table GLUO_OBJETIVO

ALTER TABLE GLUO_OBJETIVO ADD CONSTRAINT PK_OBJE PRIMARY KEY (OBJE_ID)
;

-- Table GLUO_PROGRAMA

CREATE TABLE GLUO_PROGRAMA(
 PROG_ID Serial NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 OBJE_ID Integer NOT NULL,
 DESCRIPCION Varchar NOT NULL
)
;

-- Create indexes for table GLUO_PROGRAMA

CREATE INDEX IX_OBJE_ID ON GLUO_PROGRAMA (OBJE_ID)
;

-- Add keys for table GLUO_PROGRAMA

ALTER TABLE GLUO_PROGRAMA ADD CONSTRAINT PK_PROG PRIMARY KEY (PROG_ID)
;

-- Table GLUO_SUBPROGRAMA

CREATE TABLE GLUO_SUBPROGRAMA(
 SUBP_ID Serial NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 PROG_ID Integer NOT NULL,
 DESCRIPCION Varchar NOT NULL
)
;

-- Create indexes for table GLUO_SUBPROGRAMA

CREATE INDEX IX_PROG_ID ON GLUO_SUBPROGRAMA (PROG_ID)
;

-- Add keys for table GLUO_SUBPROGRAMA

ALTER TABLE GLUO_SUBPROGRAMA ADD CONSTRAINT PK_SUBP PRIMARY KEY (SUBP_ID)
;

-- Table GLUO_PROYECTO

CREATE TABLE GLUO_PROYECTO(
 PROY_ID Serial NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 SUBP_ID Integer NOT NULL,
 DESCRIPCION Varchar NOT NULL
)
;

-- Create indexes for table GLUO_PROYECTO

CREATE INDEX IX_SUBP_ID ON GLUO_PROYECTO (SUBP_ID)
;

-- Add keys for table GLUO_PROYECTO

ALTER TABLE GLUO_PROYECTO ADD CONSTRAINT PK_PROY PRIMARY KEY (PROY_ID)
;

-- Table GLUO_INDICADOR

CREATE TABLE GLUO_INDICADOR(
 INDI_ID Serial NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 PROY_ID Integer NOT NULL,
 DESCRIPCION_INDICADOR Varchar NOT NULL,
 DESCRIPCION_LINEA_BASE Varchar NOT NULL,
 DESCRIPCION_META Varchar NOT NULL,
 VALOR_META Numeric(16,4) NOT NULL
)
;

-- Create indexes for table GLUO_INDICADOR

CREATE INDEX IX_PROY_ID ON GLUO_INDICADOR (PROY_ID)
;

-- Add keys for table GLUO_INDICADOR

ALTER TABLE GLUO_INDICADOR ADD CONSTRAINT PK_INDI PRIMARY KEY (INDI_ID)
;

-- Table GLUO_HISTORIAL_INDICADOR

CREATE TABLE GLUO_HISTORIAL_INDICADOR(
 HIIN_ID Serial NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 INDI_ID Integer NOT NULL,
 VALOR_REAL Numeric(16,4) NOT NULL,
 FECHA Timestamp NOT NULL
)
;

-- Create indexes for table GLUO_HISTORIAL_INDICADOR

CREATE INDEX IX_INDI_ID ON GLUO_HISTORIAL_INDICADOR (INDI_ID)
;

-- Add keys for table GLUO_HISTORIAL_INDICADOR

ALTER TABLE GLUO_HISTORIAL_INDICADOR ADD CONSTRAINT PK_HIIN PRIMARY KEY (HIIN_ID)
;

-- Table GLUO_DETALLE_PROYECTO

CREATE TABLE GLUO_DETALLE_PROYECTO(
 DPRO_ID Serial NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 PROY_ID Integer NOT NULL,
 ANOF_ID Integer NOT NULL,
 VALOR_TOTAL_PRESUPUESTO Numeric(16,4) NOT NULL
)
;

-- Create indexes for table GLUO_DETALLE_PROYECTO

CREATE INDEX IX_PROY_DPRO ON GLUO_DETALLE_PROYECTO (PROY_ID)
;

CREATE INDEX IX_ANOF_DPRO ON GLUO_DETALLE_PROYECTO (ANOF_ID)
;

-- Add keys for table GLUO_DETALLE_PROYECTO

ALTER TABLE GLUO_DETALLE_PROYECTO ADD CONSTRAINT PK_DPRO PRIMARY KEY (DPRO_ID)
;

-- Table GLUO_DETALLE_PROYECTO_X_RUBRO

CREATE TABLE GLUO_DETALLE_PROYECTO_X_RUBRO(
 DPRU_ID Serial NOT NULL,
 ACTIVO Character(1) NOT NULL,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 DPRO_ID Integer NOT NULL,
 DPTO_ID Integer NOT NULL,
 DESCRIPCION Varchar NOT NULL,
 VALOR Numeric(16,4) NOT NULL
)
;

-- Create indexes for table GLUO_DETALLE_PROYECTO_X_RUBRO

CREATE INDEX IX_DPRU_DPRO ON GLUO_DETALLE_PROYECTO_X_RUBRO (DPRO_ID)
;

CREATE INDEX IX_DPRU_DPTO ON GLUO_DETALLE_PROYECTO_X_RUBRO (DPTO_ID)
;

-- Add keys for table GLUO_DETALLE_PROYECTO_X_RUBRO

ALTER TABLE GLUO_DETALLE_PROYECTO_X_RUBRO ADD CONSTRAINT PK_DPRU PRIMARY KEY (DPRU_ID)
;

-- Table GLUO_TIPO_RECURSO

CREATE TABLE GLUO_TIPO_RECURSO(
 TIRE_ID Serial NOT NULL,
 CODIGO Varchar NOT NULL,
 DESCRIPCION Varchar,
 USU_CREADOR Integer NOT NULL,
 USU_MODIFICADOR Integer,
 FECHA_CREACION Timestamp NOT NULL,
 FECHA_MODIFICACION Timestamp,
 ACTIVO Character(1) NOT NULL
)
;

-- Add keys for table GLUO_TIPO_RECURSO

ALTER TABLE GLUO_TIPO_RECURSO ADD CONSTRAINT PK_TIRE PRIMARY KEY (TIRE_ID)
;

-- Create relationships section ------------------------------------------------- 

ALTER TABLE GLUO_PRESUPUESTO ADD CONSTRAINT FK_ANOF_PPTO FOREIGN KEY (ANOF_ID) REFERENCES GLUO_ANO_FISCAL (ANOF_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE GLUO_DETALLE_PRESUPUESTO ADD CONSTRAINT FK_PPTO_DPTO FOREIGN KEY (PPTO_ID) REFERENCES GLUO_PRESUPUESTO (PPTO_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE GLUO_DETALLE_PRESUPUESTO ADD CONSTRAINT FK_DPTO_DPTO FOREIGN KEY (DPTO_ID_PADRE) REFERENCES GLUO_DETALLE_PRESUPUESTO (DPTO_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE GLUO_DETALLE_PRESUPUESTO ADD CONSTRAINT FK_TIRE_DPTO FOREIGN KEY (TIRE_ID) REFERENCES GLUO_TIPO_RECURSO (TIRE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE GLUO_SECTOR_EJE_DIMENSION ADD CONSTRAINT FK_PLAN_SEDI FOREIGN KEY (PLAN_ID) REFERENCES GLUO_PLAN_DESARROLLO (PLAN_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE GLUO_OBJETIVO ADD CONSTRAINT FK_SEDI_OBJE FOREIGN KEY (SEDI_ID) REFERENCES GLUO_SECTOR_EJE_DIMENSION (SEDI_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE GLUO_PROGRAMA ADD CONSTRAINT FK_OBJE_PROG FOREIGN KEY (OBJE_ID) REFERENCES GLUO_OBJETIVO (OBJE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE GLUO_SUBPROGRAMA ADD CONSTRAINT FK_PROG_SUBP FOREIGN KEY (PROG_ID) REFERENCES GLUO_PROGRAMA (PROG_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE GLUO_PROYECTO ADD CONSTRAINT FK_SUBP_PROY FOREIGN KEY (SUBP_ID) REFERENCES GLUO_SUBPROGRAMA (SUBP_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE GLUO_INDICADOR ADD CONSTRAINT FK_PROY_INDI FOREIGN KEY (PROY_ID) REFERENCES GLUO_PROYECTO (PROY_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE GLUO_HISTORIAL_INDICADOR ADD CONSTRAINT FK_INDI_HIIN FOREIGN KEY (INDI_ID) REFERENCES GLUO_INDICADOR (INDI_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE GLUO_DETALLE_PROYECTO ADD CONSTRAINT FK_PROY_DPRO FOREIGN KEY (PROY_ID) REFERENCES GLUO_PROYECTO (PROY_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE GLUO_DETALLE_PROYECTO_X_RUBRO ADD CONSTRAINT FK_DPRO_DPRU FOREIGN KEY (DPRO_ID) REFERENCES GLUO_DETALLE_PROYECTO (DPRO_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE GLUO_DETALLE_PROYECTO_X_RUBRO ADD CONSTRAINT FK_DPTO_DPRU FOREIGN KEY (DPTO_ID) REFERENCES GLUO_DETALLE_PRESUPUESTO (DPTO_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE GLUO_DETALLE_PROYECTO ADD CONSTRAINT FK_ANOF_DPRO FOREIGN KEY (ANOF_ID) REFERENCES GLUO_ANO_FISCAL (ANOF_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE SEG_ROL_USUARIO ADD CONSTRAINT FK_USU_RLUS FOREIGN KEY (USU_ID) REFERENCES SEG_USUARIO (USU_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE SEG_ROL_USUARIO ADD CONSTRAINT FK_ROL_RLUS FOREIGN KEY (ROL_ID) REFERENCES SEG_ROL (ROL_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE SEG_PERMISO ADD CONSTRAINT FK_OPCN_PERM FOREIGN KEY (OPCN_ID) REFERENCES SEG_OPCION (OPCN_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;

ALTER TABLE SEG_PERMISO ADD CONSTRAINT FK_RLUS_PERM FOREIGN KEY (RLUS_ID) REFERENCES SEG_ROL_USUARIO (RLUS_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
;




